Update glide dependencies
pchico83/i2kit pull request #62
Opened 2018-04-05 14:16 UTC by pchico83

2018-04-05 16:28 UTC, rberrelleza approved these changes

2018-04-06 17:00 UTC, pchico83 commented on cli/providers/deploy.go
> +	case environment.AWS:
@rberrelleza I need to refactor this to have a `Provider` interface with common methods between providers of type *aws* or *kubernetes*, but due to lack of time, I will do it in a following PR.

2018-04-06 17:33 UTC, rberrelleza requested changes
Looks good, I'd like it if we had some test coverage :)

2018-04-06 17:33 UTC, rberrelleza commented on cli/providers/k8/deploy.go
> +	deploymentName := s.GetFullName(e, "-")
What's the '-' for?

2018-04-06 17:33 UTC, rberrelleza commented on cli/providers/k8/deploy.go
> +	if tmpfile != "" {
is it possible to use inmemory files instead? or the golang library demands a physical file?

2018-04-06 17:33 UTC, rberrelleza commented on cli/providers/k8/deployment/deployments.go
> +	dClient := c.AppsV1beta1().Deployments(apiv1.NamespaceDefault)
should this be parametrized, based on the k8 cluster version or something?

2018-04-06 17:33 UTC, rberrelleza commented on cli/providers/k8/deployment/translate.go
> +func Translate(s *service.Service, e *environment.Environment) *appsv1beta1.Deployment {
Can we add tests for this?

2018-04-06 17:33 UTC, rberrelleza commented on cli/providers/k8/deployment/deployments.go
> +			return fmt.Errorf("Error getting k8 deployment: %s", err)
can you mention in the error that this was after deletion?

2018-04-06 17:33 UTC, rberrelleza commented on cli/providers/k8/destroy.go
> +	log.Printf("Done!")
I'd remove this type of logs. Maybe make it a `debug.trace` if it's useful during development?

2018-04-06 17:33 UTC, rberrelleza commented on cli/providers/k8/service/services.go
> +	k8Service, err := c.CoreV1().Services("default").Get(serviceName, metav1.GetOptions{})
what's the 'default' string for?

2018-04-06 17:33 UTC, rberrelleza commented on cli/schemas/environment/environment.go
> +	Type          string    `yaml:"type,omitempty"`
I'd make this a 'providertype' type instead of string, so it's more obvious that it's a enum-like value

2018-04-06 17:33 UTC, rberrelleza commented on cli/schemas/environment/environment.go
> +	Config        string    `yaml:"config,omitempty"`
Is this meant to be the k8 config in base64?

2018-04-06 17:33 UTC, rberrelleza commented on cli/schemas/environment/environment.go
> +	err = ioutil.WriteFile(configFile.Name(), sDec, 0644)
could we make it 600, since we only need this process to use the file?

2018-04-06 17:33 UTC, rberrelleza commented on cli/schemas/environment/environment.go
> +	err = ioutil.WriteFile(configFile.Name(), sDec, 0644)
or even 400

2018-04-06 17:33 UTC, rberrelleza commented on cli/schemas/environment/environment.go
> +	return strings.ToLower(p.Type)
do we need this since the Type comes from a constant?

2018-04-06 17:33 UTC, rberrelleza commented on cli/schemas/environment/environment.go
> +		return fmt.Errorf("'provider.type' cannot be emprty")
typo

2018-04-06 17:33 UTC, rberrelleza commented on cli/schemas/environment/environment.go
> +		if p.Config == "" {
can we also validate that it's a valid base64 encoded string?

2018-04-06 18:33 UTC, pchico83 commented on cli/providers/k8/deploy.go
> +	deploymentName := s.GetFullName(e, "-")
Sometimes we need to concat the names with "."

2018-04-06 18:34 UTC, pchico83 commented on cli/providers/k8/deploy.go
> +	if tmpfile != "" {
I wouldn't do it. We should build the config data from a json, instead of encoding in base64 the full config file. This is just a temporal solution.

2018-04-06 18:35 UTC, pchico83 commented on cli/providers/k8/deployment/deployments.go
> +	dClient := c.AppsV1beta1().Deployments(apiv1.NamespaceDefault)
Probably, but I wouldn't bother about this for now. If we push the k8 implementation, we will need to parameterize a lot of things.

2018-04-06 18:37 UTC, pchico83 commented on cli/providers/k8/deployment/deployments.go
> +			return fmt.Errorf("Error getting k8 deployment: %s", err)
There is a previous log message that indicates that.

2018-04-06 18:38 UTC, pchico83 commented on cli/providers/k8/destroy.go
> +	log.Printf("Done!")
It is to indicate the end of the operation. `docker-compose`for example adds a *Done!* message after every operation.

2018-04-06 18:38 UTC, pchico83 commented on cli/providers/k8/service/services.go
> +	k8Service, err := c.CoreV1().Services("default").Get(serviceName, metav1.GetOptions{})
It is to access different namespaces. I think we should create a namespace with the name of the current environment and create the different resource objects there.
I have created a issue for it.

2018-04-06 18:40 UTC, pchico83 commented on cli/schemas/environment/environment.go
> +	Type          string    `yaml:"type,omitempty"`
Agree. I will do it as part of refactoring "aws" and "k8" in a common interface.

2018-04-06 18:40 UTC, pchico83 commented on cli/schemas/environment/environment.go
> +	Config        string    `yaml:"config,omitempty"`
Yeap

2018-04-06 18:41 UTC, pchico83 commented on cli/schemas/environment/environment.go
> +	err = ioutil.WriteFile(configFile.Name(), sDec, 0644)
done

2018-04-06 18:41 UTC, pchico83 commented on cli/schemas/environment/environment.go
> +	return strings.ToLower(p.Type)
I will remove it when creating the providertype type

2018-04-06 18:41 UTC, pchico83 commented on cli/schemas/environment/environment.go
> +		return fmt.Errorf("'provider.type' cannot be emprty")
fixed

2018-04-06 18:43 UTC, pchico83 commented on cli/schemas/environment/environment.go
> +		if p.Config == "" {
done

2018-04-06 19:25 UTC, merged